### ISSUE TITLE
[Feature Request] - unopinionated settings for consumers 

### ISSUE THREAD

**Issue by EvanBurbidge** [EvanBurbidge/rabbitmq-amqp-interface#3]
Some users want to set their own settings allow them to pass, queue, channel and exchange settings into a function call.

**Comment by thewebuiguy** [comment]
https://github.com/EvanBurbidge/rabbitode/commit/8cd6e356aadaa29d42fa438ff59a8178d247ee58 

tried to make everything as configurable as possible
