### ISSUE TITLE
Add typings file

### ISSUE THREAD

**Issue by kaburkett** [EvanBurbidge/rabbitmq-amqp-interface#7]
Unable to see implementation from ide because there is no typings file. RabbitMqInterface is by default type any.

**Comment by thewebuiguy** [comment]
@kaburkett should I try add it to definitely typed or just add a .d.ts file to the package.json?

**Comment by thewebuiguy** [comment]
Solve 4f2fd07784be41fffe8a4a401fe12ea4cc98c5fb 

basic typings for now but will go deeper at a later stage.
